
class Constantes:
    MOTOR_ORDER_APM='APM'
    MOTOR_ORDER_CPM='CPM'
    MOTOR_ORDER_UNKNOWN='UNKNOWN'
    DATETIME_FORMAT='%Y-%m-%dT%H:%M:%SZ'
    ELK_DATETIME_FORMAT='%Y-%m-%dT%H:%M:%S.%fZ'
    ELK_MAX_RECORDS_COUNT=1000
    ELK_SCROLL_TIME="30m"
  
 