# Generated by Django 2.2.3 on 2019-07-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('cod_apertura', models.TextField()),
                ('subcodigo', models.TextField()),
                ('plantilla', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
