from django.db import models
import django.db.models.options as options
options.DEFAULT_NAMES = options.DEFAULT_NAMES + ('in_db',)

# Create your models here.

class Site(models.Model):

    objid = models.FloatField(blank=True, primary_key=True)
    site_id = models.CharField(max_length=80, blank=True, null=True)
    name = models.CharField(max_length=80, blank=True, null=True)
    s_name = models.CharField(max_length=80, blank=True, null=True)
    external_id = models.CharField(max_length=80, blank=True, null=True)
    type = models.FloatField(blank=True, null=True)
    logistics_type = models.FloatField(blank=True, null=True)
    is_support = models.FloatField(blank=True, null=True)
    region = models.CharField(max_length=80, blank=True, null=True)
    s_region = models.CharField(max_length=80, blank=True, null=True)
    district = models.CharField(max_length=80, blank=True, null=True)
    s_district = models.CharField(max_length=80, blank=True, null=True)
    depot = models.CharField(max_length=80, blank=True, null=True)
    contr_login = models.CharField(max_length=80, blank=True, null=True)
    contr_passwd = models.CharField(max_length=80, blank=True, null=True)
    is_default = models.FloatField(blank=True, null=True)
    notes = models.CharField(max_length=255, blank=True, null=True)
    spec_consid = models.FloatField(blank=True, null=True)
    mdbk = models.CharField(max_length=80, blank=True, null=True)
    state_code = models.FloatField(blank=True, null=True)
    state_value = models.CharField(max_length=20, blank=True, null=True)
    industry_type = models.CharField(max_length=40, blank=True, null=True)
    appl_type = models.CharField(max_length=40, blank=True, null=True)
    cut_date = models.DateTimeField(blank=True, null=True)
    site_type = models.CharField(max_length=4, blank=True, null=True)
    status = models.FloatField(blank=True, null=True)
    arch_ind = models.FloatField(blank=True, null=True)
    alert_ind = models.FloatField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    fax = models.CharField(max_length=20, blank=True, null=True)
    dev = models.FloatField(blank=True, null=True)
    update_stamp = models.DateTimeField(blank=True, null=True)
    ship_via = models.CharField(max_length=80, blank=True, null=True)
    blg_evt_gen_sts = models.FloatField(blank=True, null=True)
    x_tipo = models.CharField(max_length=1, blank=True, null=True)
    x_e_mail = models.CharField(max_length=80, blank=True, null=True)
    x_pais = models.CharField(max_length=1, blank=True, null=True)
    x_dir_primaria = models.CharField(max_length=1, blank=True, null=True)
    child_site2site = models.FloatField(blank=True, null=True)
    support_office2site = models.FloatField(blank=True, null=True)
    cust_primaddr2address = models.FloatField(blank=True, null=True)
    cust_billaddr2address = models.FloatField(blank=True, null=True)
    cust_shipaddr2address = models.FloatField(blank=True, null=True)
    site_support2employee = models.FloatField(blank=True, null=True)
    site_altsupp2employee = models.FloatField(blank=True, null=True)
    report_site2bug = models.FloatField(blank=True, null=True)
    primary2bus_org = models.FloatField(blank=True, null=True)
    site2exch_protocol = models.FloatField(blank=True, null=True)
    x_site_tecnicos2site = models.FloatField(blank=True, null=True)
    site2x_nodo = models.FloatField(blank=True, null=True)
    x_compania = models.CharField(max_length=2, blank=True, null=True)
    x_division = models.CharField(max_length=2, blank=True, null=True)
    x_estado_catv = models.CharField(max_length=40, blank=True, null=True)
    x_estado_cliente = models.CharField(max_length=40, blank=True, null=True)
    x_estado_dtv = models.CharField(max_length=40, blank=True, null=True)
    x_estado_int = models.CharField(max_length=50, blank=True, null=True)
    x_estado_tlf = models.CharField(max_length=40, blank=True, null=True)
    x_fecha_estado = models.DateTimeField(blank=True, null=True)
    x_flag_locator_code = models.CharField(max_length=1, blank=True, null=True)
    x_franquicia = models.CharField(max_length=3, blank=True, null=True)
    x_locator_code = models.CharField(max_length=4, blank=True, null=True)
    x_pool = models.CharField(max_length=1, blank=True, null=True)
    x_price_code = models.CharField(max_length=2, blank=True, null=True)
    x_segmento_cli = models.CharField(max_length=2, blank=True, null=True)
    x_tipo_clte = models.CharField(max_length=2, blank=True, null=True)
    x_tipo_ggcc = models.CharField(max_length=12, blank=True, null=True)
    site2x_det_site = models.FloatField(blank=True, null=True)
    x_site2bill = models.FloatField(blank=True, null=True)
    x_estado_int_ull = models.CharField(max_length=40, blank=True, null=True)
    x_estado_tlf_ull = models.CharField(max_length=40, blank=True, null=True)
    x_agencia_recobro = models.CharField(max_length=8, blank=True, null=True)
    x_secuencial_adsl = models.FloatField(blank=True, null=True)
    x_secuencial_data = models.FloatField(blank=True, null=True)
    x_jerarquia = models.CharField(max_length=20, blank=True, null=True)
    x_child_site2x_site = models.FloatField(blank=True, null=True)
    x_estado_mv = models.CharField(max_length=40, blank=True, null=True)
    x_estado_adsli = models.CharField(max_length=40, blank=True, null=True)
    x_estado_ai = models.CharField(max_length=40, blank=True, null=True)
    x_autoriza_com = models.CharField(max_length=30, blank=True, null=True)
    guid = models.CharField(max_length=31, blank=True, null=True)
    loc_role2hgbst_elm = models.FloatField(blank=True, null=True)
    loc_type2hgbst_elm = models.FloatField(blank=True, null=True)
    site_app2hgbst_elm = models.FloatField(blank=True, null=True)
    site_ind2hgbst_elm = models.FloatField(blank=True, null=True)
    site_ship2hgbst_elm = models.FloatField(blank=True, null=True)
    x_site_obsoleto = models.FloatField(blank=True, null=True)
    x_fecha_obsoleto = models.DateTimeField(blank=True, null=True)
    x_dir_social = models.CharField(max_length=1, blank=True, null=True)
    x_tecnologia_ins = models.CharField(max_length=5, blank=True, null=True)
    x_nds_atencion = models.CharField(max_length=255, blank=True, null=True)
    x_agente_egc = models.CharField(max_length=255, blank=True, null=True)
    x_lortado = models.CharField(max_length=2, blank=True, null=True)
    x_estado_acc_ctrl = models.CharField(max_length=3, blank=True, null=True)
    x_motivo_acc_ctrl = models.CharField(max_length=60, blank=True, null=True)
    x_perfil_acc_ctrl = models.CharField(max_length=80, blank=True, null=True)
    x_pull_list = models.CharField(max_length=1, blank=True, null=True)
    x_robinson = models.CharField(max_length=1, blank=True, null=True)
    x_cliente_prueba = models.FloatField(blank=True, null=True)
    x_fecha_migracion = models.DateTimeField(blank=True, null=True)
    x_soc_serv_fijo = models.CharField(max_length=10, blank=True, null=True)
    x_centro_coste = models.CharField(max_length=80, blank=True, null=True)
    x_tipo_op_acc_ctrl = models.CharField(max_length=1, blank=True, null=True)
    x_nat = models.CharField(max_length=6, blank=True, null=True)
    x_nateable = models.CharField(max_length=6, blank=True, null=True)
    x_fecha_nateable = models.DateTimeField(blank=True, null=True)
    x_tecnologia_ins_mig = models.CharField(max_length=5, blank=True, null=True)
    x_sociedad_facturadora = models.CharField(max_length=10, blank=True, null=True)

    
    def __json_encode__(self):
        output={}
        for field in self._meta.fields:
            output[field.name]=getattr(self, field.name)
        return output    
        

    class Meta:
        in_db = 'smart_gg'
        managed = False
        db_table = '\"SA\".\"TABLE_SITE\"'

